
// --- AÉROPORTS INTERNATIONAUX (Extraction : Aeroport internationaux.txt) ---
export const AIRPORTS = [
  // Afrique centrale
  "Douala, Cameroun (Aéroport)",
  "Garoua, Cameroun (Aéroport)",
  "Maroua Salak, Cameroun (Aéroport)",
  "Yaoundé-Nsimalen, Cameroun (Aéroport)",
  "Yaoundé-Ville, Cameroun (Aéroport)",
  "Mbujimayi (Bipemba), RDC (Aéroport)",
  "Goma, RDC (Aéroport)",
  "Kinshasa (Ndjili), RDC (Aéroport)",
  "Kisangani (Bangoka), RDC (Aéroport)",
  "Lubumbashi, RDC (Aéroport)",
  "Brazzaville (Maya-Maya), Congo (Aéroport)",
  "Pointe-Noire (Agostinho-Neto), Congo (Aéroport)",
  "Malabo, Guinée Équatoriale (Aéroport)",
  "Mengomeyén (Obiang Nguema), Guinée Équatoriale (Aéroport)",
  "Libreville (Léon-Mba), Gabon (Aéroport)",
  "Port-Gentil, Gabon (Aéroport)",
  "Franceville, Gabon (Aéroport)",
  "São Tomé, São Tomé et Príncipe (Aéroport)",

  // Afrique de l'Est
  "Bujumbura, Burundi (Aéroport)",
  "Moroni (Hahaya), Comores (Aéroport)",
  "Eldoret, Kenya (Aéroport)",
  "Mombasa (Moi), Kenya (Aéroport)",
  "Kisumu, Kenya (Aéroport)",
  "Nairobi (Jomo-Kenyatta), Kenya (Aéroport)",
  "Plaine Magnien (Sir-Seewoosagur-Ramgoolam), Maurice (Aéroport)",
  "Sainte-Marie (Roland-Garros), La Réunion (Aéroport)",
  "Kigali, Rwanda (Aéroport)",
  "Victoria, Seychelles (Aéroport)",
  "Djouba, Soudan du Sud (Aéroport)",
  "Dar es Salam (Julius-Nyerere), Tanzanie (Aéroport)",
  "Kilimandjaro (Arusha/Moshi), Tanzanie (Aéroport)",
  "Zanzibar, Tanzanie (Aéroport)",
  "Entebbe, Ouganda (Aéroport)",

  // Corne de l'Afrique
  "Djibouti (Ambouli), Djibouti (Aéroport)",
  "Asmara, Érythrée (Aéroport)",
  "Addis-Abeba (Bole), Éthiopie (Aéroport)",
  "Dire Dawa, Éthiopie (Aéroport)",
  "Mogadiscio, Somalie (Aéroport)",
  "Hargeisa, Somalie (Aéroport)",

  // Afrique du Nord
  "Alger (Houari Boumédiène), Algérie (Aéroport)",
  "Annaba (Rabah-Bitat), Algérie (Aéroport)",
  "Constantine (Mohamed Boudiaf), Algérie (Aéroport)",
  "Oran (Ahmed Ben Bella), Algérie (Aéroport)",
  "Le Caire, Égypte (Aéroport)",
  "Alexandrie (Borg El Arab), Égypte (Aéroport)",
  "Hurghada, Égypte (Aéroport)",
  "Charm el-Cheikh, Égypte (Aéroport)",
  "Benghazi (Benina), Libye (Aéroport)",
  "Tripoli (Mitiga), Libye (Aéroport)",
  "Casablanca (Mohammed-V), Maroc (Aéroport)",
  "Marrakech (Ménara), Maroc (Aéroport)",
  "Agadir (Al Massira), Maroc (Aéroport)",
  "Fès (Saïss), Maroc (Aéroport)",
  "Tanger (Ibn Battouta), Maroc (Aéroport)",
  "Rabat (Salé), Maroc (Aéroport)",
  "Khartoum, Soudan (Aéroport)",
  "N'Djaména, Tchad (Aéroport)",
  "Tunis (Carthage), Tunisie (Aéroport)",
  "Djerba (Zarzis), Tunisie (Aéroport)",
  "Monastir (Habib-Bourguiba), Tunisie (Aéroport)",

  // Afrique australe
  "Le Cap, Afrique du Sud (Aéroport)",
  "Johannesbourg (OR Tambo), Afrique du Sud (Aéroport)",
  "Durban (King Shaka), Afrique du Sud (Aéroport)",
  "Luanda (Quatro de Fevereiro), Angola (Aéroport)",
  "Gaborone, Botswana (Aéroport)",
  "Antananarivo (Ivato), Madagascar (Aéroport)",
  "Nosy Be (Fascene), Madagascar (Aéroport)",
  "Lilongwe, Malawi (Aéroport)",
  "Maputo, Mozambique (Aéroport)",
  "Windhoek (Hosea Kutako), Namibie (Aéroport)",
  "Lusaka, Zambie (Aéroport)",
  "Harare, Zimbabwe (Aéroport)",
  "Victoria Falls, Zimbabwe (Aéroport)",

  // Afrique de l'Ouest
  "Cotonou, Bénin (Aéroport)",
  "Ouagadougou, Burkina Faso (Aéroport)",
  "Bobo-Dioulasso, Burkina Faso (Aéroport)",
  "Praia, Cap-Vert (Aéroport)",
  "Sal (Amílcar-Cabral), Cap-Vert (Aéroport)",
  "Bangui (M'Poko), Centrafrique (Aéroport)",
  "Abidjan (Félix-Houphouët-Boigny), Côte d'Ivoire (Aéroport)",
  "Banjul, Gambie (Aéroport)",
  "Accra (Kotoka), Ghana (Aéroport)",
  "Conakry, Guinée (Aéroport)",
  "Bissau (Osvaldo Vieira), Guinée-Bissau (Aéroport)",
  "Monrovia (Roberts), Liberia (Aéroport)",
  "Bamako (Sénou), Mali (Aéroport)",
  "Nouakchott (Oumtounsy), Mauritanie (Aéroport)",
  "Niamey (Diori Hamani), Niger (Aéroport)",
  "Lagos (Murtala-Muhammed), Nigeria (Aéroport)",
  "Abuja (Nnamdi Azikiwe), Nigeria (Aéroport)",
  "Port Harcourt, Nigeria (Aéroport)",
  "Dakar (Blaise-Diagne), Sénégal (Aéroport)",
  "Freetown (Lungi), Sierra Leone (Aéroport)",
  "Lomé (Tokoin), Togo (Aéroport)",

  // Amérique (Caraïbes)
  "Nassau (Lynden Pindling), Bahamas (Aéroport)",
  "La Havane (José Martí), Cuba (Aéroport)",
  "Varadero (Juan Gualberto Gómez), Cuba (Aéroport)",
  "Punta Cana, République dominicaine (Aéroport)",
  "Saint-Domingue (Las Américas), République dominicaine (Aéroport)",
  "Pointe-à-Pitre (Pôle Caraïbes), Guadeloupe (Aéroport)",
  "Port-au-Prince (Toussaint-Louverture), Haïti (Aéroport)",
  "Kingston (Norman-Manley), Jamaïque (Aéroport)",
  "Fort-de-France (Aimé-Césaire), Martinique (Aéroport)",
  "San Juan (Luis Muñoz Marín), Porto Rico (Aéroport)",

  // Amérique du Nord
  "Montréal (Pierre-Elliott-Trudeau), Canada (Aéroport)",
  "Toronto (Pearson), Canada (Aéroport)",
  "Vancouver, Canada (Aéroport)",
  "Québec (Jean-Lesage), Canada (Aéroport)",
  "Mexico (Benito Juárez), Mexique (Aéroport)",
  "Cancún, Mexique (Aéroport)",
  "New York (JFK), USA (Aéroport)",
  "New York (LaGuardia), USA (Aéroport)",
  "Newark (Liberty), USA (Aéroport)",
  "Los Angeles (LAX), USA (Aéroport)",
  "Chicago (O'Hare), USA (Aéroport)",
  "Atlanta (Hartsfield-Jackson), USA (Aéroport)",
  "Miami, USA (Aéroport)",
  "Dallas/Fort Worth, USA (Aéroport)",
  "San Francisco, USA (Aéroport)",
  "Washington (Dulles), USA (Aéroport)",
  "Houston (George-Bush), USA (Aéroport)",
  "Boston (Logan), USA (Aéroport)",
  "Orlando, USA (Aéroport)",
  "Seattle (Tacoma), USA (Aéroport)",

  // Amérique du Sud
  "Buenos Aires (Ezeiza), Argentine (Aéroport)",
  "La Paz (El Alto), Bolivie (Aéroport)",
  "São Paulo (Guarulhos), Brésil (Aéroport)",
  "Rio de Janeiro (Galeão), Brésil (Aéroport)",
  "Brasília, Brésil (Aéroport)",
  "Santiago (Arturo-Merino-Benítez), Chili (Aéroport)",
  "Bogota (El Dorado), Colombie (Aéroport)",
  "Medellín (José María Córdova), Colombie (Aéroport)",
  "Quito (Mariscal Sucre), Équateur (Aéroport)",
  "Guayaquil (José Joaquín de Olmedo), Équateur (Aéroport)",
  "Cayenne (Félix Éboué), Guyane Française (Aéroport)",
  "Lima (Jorge Chávez), Pérou (Aéroport)",
  "Caracas (Simón Bolívar), Venezuela (Aéroport)",

  // Asie
  "Pékin (Capital), Chine (Aéroport)",
  "Shanghai (Pudong), Chine (Aéroport)",
  "Shanghai (Hongqiao), Chine (Aéroport)",
  "Canton (Baiyun), Chine (Aéroport)",
  "Hong Kong, Chine (Aéroport)",
  "Tokyo (Narita), Japon (Aéroport)",
  "Tokyo (Haneda), Japon (Aéroport)",
  "Osaka (Kansai), Japon (Aéroport)",
  "Séoul (Incheon), Corée du Sud (Aéroport)",
  "Taipei (Taoyuan), Taïwan (Aéroport)",
  "Delhi (Indira Gandhi), Inde (Aéroport)",
  "Bombay (Chhatrapati-Shivaji), Inde (Aéroport)",
  "Bangalore (Kempegowda), Inde (Aéroport)",
  "Jakarta (Soekarno-Hatta), Indonésie (Aéroport)",
  "Bali (Denpasar - Ngurah Rai), Indonésie (Aéroport)",
  "Kuala Lumpur, Malaisie (Aéroport)",
  "Singapour (Changi), Singapour (Aéroport)",
  "Bangkok (Suvarnabhumi), Thaïlande (Aéroport)",
  "Phuket, Thaïlande (Aéroport)",
  "Hanoi (Nội Bài), Vietnam (Aéroport)",
  "Ho Chi Minh Ville (Tân Sơn Nhất), Vietnam (Aéroport)",

  // Moyen-Orient
  "Dubaï (DXB), Émirats arabes unis (Aéroport)",
  "Abu Dhabi, Émirats arabes unis (Aéroport)",
  "Doha (Hamad), Qatar (Aéroport)",
  "Riyad (Roi Khaled), Arabie saoudite (Aéroport)",
  "Djeddah (Roi-Abdelaziz), Arabie saoudite (Aéroport)",
  "Tel Aviv (Ben Gourion), Israël (Aéroport)",
  "Beyrouth (Rafic Hariri), Liban (Aéroport)",
  "Istanbul (IST), Turquie (Aéroport)",
  "Istanbul (Sabiha Gökçen), Turquie (Aéroport)",
  "Antalya, Turquie (Aéroport)",

  // Europe
  "Paris (CDG), France (Aéroport)",
  "Paris (Orly), France (Aéroport)",
  "Nice (Côte d'Azur), France (Aéroport)",
  "Lyon (Saint-Exupéry), France (Aéroport)",
  "Marseille (Provence), France (Aéroport)",
  "Londres (Heathrow), Royaume-Uni (Aéroport)",
  "Londres (Gatwick), Royaume-Uni (Aéroport)",
  "Francfort, Allemagne (Aéroport)",
  "Munich, Allemagne (Aéroport)",
  "Amsterdam (Schiphol), Pays-Bas (Aéroport)",
  "Bruxelles (Zaventem), Belgique (Aéroport)",
  "Madrid (Barajas), Espagne (Aéroport)",
  "Barcelone (El Prat), Espagne (Aéroport)",
  "Rome (Fiumicino), Italie (Aéroport)",
  "Milan (Malpensa), Italie (Aéroport)",
  "Zurich, Suisse (Aéroport)",
  "Genève, Suisse (Aéroport)",
  "Vienne, Autriche (Aéroport)",
  "Moscou (Cheremetievo), Russie (Aéroport)",
  "Moscou (Domodedovo), Russie (Aéroport)",
  "Lisbonne (Portela), Portugal (Aéroport)",
  "Athènes (Elefthérios-Venizélos), Grèce (Aéroport)",
  "Dublin, Irlande (Aéroport)",
  "Copenhague, Danemark (Aéroport)",
  "Stockholm (Arlanda), Suède (Aéroport)",
  "Oslo (Gardermoen), Norvège (Aéroport)",
  "Helsinki (Vantaa), Finlande (Aéroport)",
  "Varsovie (Chopin), Pologne (Aéroport)",
  "Kiev (Boryspil), Ukraine (Aéroport)",

  // Océanie
  "Sydney (Kingsford Smith), Australie (Aéroport)",
  "Melbourne (Tullamarine), Australie (Aéroport)",
  "Brisbane, Australie (Aéroport)",
  "Perth, Australie (Aéroport)",
  "Auckland, Nouvelle-Zélande (Aéroport)",
  "Nouméa (La Tontouta), Nouvelle-Calédonie (Aéroport)",
  "Papeete (Tahiti Fa'a'ā), Polynésie française (Aéroport)",
];

// --- PORTS MARITIMES (Extraction : Liste des ports maritimes.txt) ---
export const SEAPORTS = [
  // Afrique
  "Alger, Algérie (Port)",
  "Oran, Algérie (Port)",
  "Bejaia, Algérie (Port)",
  "Skikda, Algérie (Port)",
  "Luanda, Angola (Port)",
  "Lobito, Angola (Port)",
  "Cotonou, Bénin (Port)",
  "Douala, Cameroun (Port)",
  "Kribi, Cameroun (Port)",
  "Pointe-Noire, Congo (Port)",
  "Matadi, RDC (Port)",
  "Boma, RDC (Port)",
  "Abidjan, Côte d'Ivoire (Port)",
  "San Pedro, Côte d'Ivoire (Port)",
  "Djibouti, Djibouti (Port)",
  "Alexandrie, Égypte (Port)",
  "Port-Saïd, Égypte (Port)",
  "Damiette, Égypte (Port)",
  "Suez, Égypte (Port)",
  "Libreville (Owendo), Gabon (Port)",
  "Port-Gentil, Gabon (Port)",
  "Tema, Ghana (Port)",
  "Takoradi, Ghana (Port)",
  "Conakry, Guinée (Port)",
  "Bissau, Guinée-Bissau (Port)",
  "Mombasa, Kenya (Port)",
  "Monrovia, Liberia (Port)",
  "Tripoli, Libye (Port)",
  "Benghazi, Libye (Port)",
  "Misrata, Libye (Port)",
  "Toamasina (Tamatave), Madagascar (Port)",
  "Casablanca, Maroc (Port)",
  "Tanger Med, Maroc (Port)",
  "Agadir, Maroc (Port)",
  "Port-Louis, Maurice (Port)",
  "Nouakchott, Mauritanie (Port)",
  "Nouadhibou, Mauritanie (Port)",
  "Maputo, Mozambique (Port)",
  "Beira, Mozambique (Port)",
  "Walvis Bay, Namibie (Port)",
  "Lagos (Apapa), Nigeria (Port)",
  "Lagos (Tincan), Nigeria (Port)",
  "Port Harcourt (Onne), Nigeria (Port)",
  "Le Port (Pointe des Galets), La Réunion (Port)",
  "Dakar, Sénégal (Port)",
  "Victoria, Seychelles (Port)",
  "Mogadiscio, Somalie (Port)",
  "Berbera, Somalie (Port)",
  "Port-Soudan, Soudan (Port)",
  "Dar es Salam, Tanzanie (Port)",
  "Zanzibar, Tanzanie (Port)",
  "Lomé, Togo (Port)",
  "Radès (Tunis), Tunisie (Port)",
  "Sfax, Tunisie (Port)",
  "Durban, Afrique du Sud (Port)",
  "Le Cap, Afrique du Sud (Port)",
  "Port Elizabeth, Afrique du Sud (Port)",

  // Amériques
  "Buenos Aires, Argentine (Port)",
  "Santos, Brésil (Port)",
  "Rio de Janeiro, Brésil (Port)",
  "Paranaguá, Brésil (Port)",
  "Halifax, Canada (Port)",
  "Montréal, Canada (Port)",
  "Vancouver, Canada (Port)",
  "San Antonio, Chili (Port)",
  "Valparaíso, Chili (Port)",
  "Buenaventura, Colombie (Port)",
  "Carthagène, Colombie (Port)",
  "La Havane, Cuba (Port)",
  "Guayaquil, Équateur (Port)",
  "New York / New Jersey, USA (Port)",
  "Los Angeles, USA (Port)",
  "Long Beach, USA (Port)",
  "Savannah, USA (Port)",
  "Houston, USA (Port)",
  "Miami, USA (Port)",
  "Seattle, USA (Port)",
  "Norfolk, USA (Port)",
  "Oakland, USA (Port)",
  "Veracruz, Mexique (Port)",
  "Manzanillo, Mexique (Port)",
  "Altamira, Mexique (Port)",
  "Balboa, Panama (Port)",
  "Colon, Panama (Port)",
  "Callao (Lima), Pérou (Port)",
  "Montevideo, Uruguay (Port)",
  "La Guaira, Venezuela (Port)",
  "Puerto Cabello, Venezuela (Port)",
  "Cayenne (Degrad des Cannes), Guyane Française (Port)",
  "Fort-de-France, Martinique (Port)",
  "Pointe-à-Pitre (Jarry), Guadeloupe (Port)",

  // Asie
  "Shanghai, Chine (Port)",
  "Ningbo-Zhoushan, Chine (Port)",
  "Shenzhen, Chine (Port)",
  "Guangzhou, Chine (Port)",
  "Qingdao, Chine (Port)",
  "Tianjin, Chine (Port)",
  "Xiamen, Chine (Port)",
  "Dalian, Chine (Port)",
  "Hong Kong, Chine (Port)",
  "Busan, Corée du Sud (Port)",
  "Incheon, Corée du Sud (Port)",
  "Nhava Sheva (Mumbai), Inde (Port)",
  "Chennai, Inde (Port)",
  "Mundra, Inde (Port)",
  "Kolkata (Calcutta), Inde (Port)",
  "Tanjung Priok (Jakarta), Indonésie (Port)",
  "Surabaya, Indonésie (Port)",
  "Tokyo, Japon (Port)",
  "Yokohama, Japon (Port)",
  "Kobe, Japon (Port)",
  "Osaka, Japon (Port)",
  "Nagoya, Japon (Port)",
  "Port Kelang, Malaisie (Port)",
  "Tanjung Pelepas, Malaisie (Port)",
  "Karachi, Pakistan (Port)",
  "Manille, Philippines (Port)",
  "Singapour, Singapour (Port)",
  "Colombo, Sri Lanka (Port)",
  "Kaohsiung, Taïwan (Port)",
  "Keelung, Taïwan (Port)",
  "Laem Chabang (Bangkok), Thaïlande (Port)",
  "Ho Chi Minh Ville (Cat Lai), Vietnam (Port)",
  "Haiphong, Vietnam (Port)",
  "Da Nang, Vietnam (Port)",

  // Moyen-Orient
  "Jebel Ali (Dubaï), EAU (Port)",
  "Abu Dhabi (Khalifa), EAU (Port)",
  "Dammam, Arabie Saoudite (Port)",
  "Djeddah, Arabie Saoudite (Port)",
  "Bandar Abbas, Iran (Port)",
  "Umm Qasr, Irak (Port)",
  "Haïfa, Israël (Port)",
  "Ashdod, Israël (Port)",
  "Aqaba, Jordanie (Port)",
  "Koweït (Shuwaikh), Koweït (Port)",
  "Beyrouth, Liban (Port)",
  "Salalah, Oman (Port)",
  "Sohar, Oman (Port)",
  "Hamad, Qatar (Port)",
  "Lattaquié, Syrie (Port)",
  "Mersin, Turquie (Port)",
  "Istanbul (Ambarli), Turquie (Port)",
  "Izmir, Turquie (Port)",
  "Aden, Yémen (Port)",

  // Europe
  "Anvers, Belgique (Port)",
  "Zeebrugge, Belgique (Port)",
  "Hambourg, Allemagne (Port)",
  "Bremerhaven, Allemagne (Port)",
  "Rotterdam, Pays-Bas (Port)",
  "Le Havre (Haropa), France (Port)",
  "Marseille (Fos), France (Port)",
  "Dunkerque, France (Port)",
  "Algésiras, Espagne (Port)",
  "Valence, Espagne (Port)",
  "Barcelone, Espagne (Port)",
  "Bilbao, Espagne (Port)",
  "Felixstowe, Royaume-Uni (Port)",
  "Southampton, Royaume-Uni (Port)",
  "Londres (Gateway/Tilbury), Royaume-Uni (Port)",
  "Liverpool, Royaume-Uni (Port)",
  "Gênes, Italie (Port)",
  "Gioia Tauro, Italie (Port)",
  "La Spezia, Italie (Port)",
  "Trieste, Italie (Port)",
  "Le Pirée, Grèce (Port)",
  "Thessalonique, Grèce (Port)",
  "Gdansk, Pologne (Port)",
  "Gdynia, Pologne (Port)",
  "Saint-Pétersbourg, Russie (Port)",
  "Novorossiysk, Russie (Port)",
  "Constanța, Roumanie (Port)",
  "Koper, Slovénie (Port)",
  "Sines, Portugal (Port)",
  "Lisbonne, Portugal (Port)",
  "Leixões (Porto), Portugal (Port)",

  // Océanie
  "Sydney (Botany Bay), Australie (Port)",
  "Melbourne, Australie (Port)",
  "Brisbane, Australie (Port)",
  "Fremantle (Perth), Australie (Port)",
  "Auckland, Nouvelle-Zélande (Port)",
  "Tauranga, Nouvelle-Zélande (Port)",
  "Lyttelton (Christchurch), Nouvelle-Zélande (Port)",
  "Nouméa, Nouvelle-Calédonie (Port)",
  "Papeete, Polynésie Française (Port)",
  "Suva, Fidji (Port)"
];

// Pour compatibilité si besoin, on peut garder LOCATIONS combiné ou le supprimer
export const LOCATIONS = [...AIRPORTS, ...SEAPORTS];
